### PR TITLE
import generete_tesseract_results

### PR DESCRIPTION
**Pull request by darsh169**
minor change

### CODE REVIEW

**Review by CS-savvy — CHANGES_REQUESTED** [review]
There is no functional difference.

**Comment by darsh169** [comment]
> There is no functional difference.

isn't inference.py used for training purpose?

**Comment by CS-savvy** [comment]
Yes, I can't see any difference between the two scripts apart you have removed called main() function. May I know what is the reason behind removing that ?

**Comment by darsh169** [comment]
its not --from utils import gererate_tesseract_results
but-- import gererate_tesseract_results

**Comment by CS-savvy** [comment]
Oh my bad

**Review by CS-savvy — COMMENTED** [review]
We can merge this to master

**Review by CS-savvy — APPROVED** [review]

**Pull request merged**
